name: web_view
version: 1.1.2

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  onesignal_flutter: ^3.0.0
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.4

  # load and display html
  webview_flutter: ^3.0.0

  pull_to_refresh: ^2.0.0
  firebase_core: ^2.1.1
  firebase_messaging: ^14.0.3
  device_info_plus: ^8.0.0
  cloud_firestore: ^4.0.4
  shared_preferences: ^2.0.15
  is_first_run: ^1.0.0
  http: ^0.13.5
  mobile_scanner: ^2.0.0
  provider: ^6.0.4
  qr_flutter: ^4.0.0
  fluttertoast: ^8.1.1
  path_provider: ^2.0.11
  image_picker: ^0.8.6
  share_plus: ^6.3.0
  flutter_expandable_fab: ^1.6.0
  functional_listener: ^2.1.0
  property_change_notifier: ^0.3.0
  easy_search_bar: ^2.4.2
  anim_search_bar: ^2.0.2
  flutter_search_bar: ^2.1.0
  wp_search_bar: ^0.0.6
  outline_search_bar: ^2.3.0
  app_bar_with_search_switch: ^1.3.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4

flutter:
  assets:
  - assets/urpointlogo.png
  - assets/
  - assets/QrEmbedUrPoint.png
  - UrIcons/
  - assets/Bell/
  uses-material-design: true
