name: web_view
version: 1.1.1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  onesignal_flutter: ^3.0.0
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.4

  # load and display html
  webview_flutter: ^3.0.0

  pull_to_refresh: ^2.0.0
  firebase_core: ^2.1.1
  firebase_messaging: ^14.0.3
  device_info_plus: ^8.0.0
  cloud_firestore: ^4.0.4
  shared_preferences: ^2.0.15
  is_first_run: ^1.0.0
  http: ^0.13.5
  mobile_scanner: ^2.0.0
  provider: ^6.0.4
  flutter_statusbar_manager: ^2.0.0
  qr_flutter: ^4.0.0
  gallery_saver: ^2.3.2
  fluttertoast: ^8.1.1
  path_provider: ^2.0.11
  image_picker: ^0.8.6
  share_plus: ^6.3.0
  flutter_expandable_fab: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4

flutter:
  assets:
  - assets/urpointlogo.png
  - assets/
  - assets/QrEmbedUrPoint.png
  uses-material-design: true
