name: web_view
version: 1.1.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  onesignal_flutter: ^3.0.0
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.4

  # load and display html
  webview_flutter: ^3.0.0

  pull_to_refresh: ^2.0.0
  firebase_core: ^2.1.1
  firebase_messaging: ^14.0.3
  device_info_plus: ^8.0.0
  cloud_firestore: ^4.0.4
  shared_preferences: ^2.0.15
  is_first_run: ^1.0.0
  http: ^0.13.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true
