// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIYMY_cf5pJuZo_GfMRcFCzO_i77pVq4k',
    appId: '1:5042694816:web:d7f785256fc69e4987f7c5',
    messagingSenderId: '5042694816',
    projectId: 'ur-point',
    authDomain: 'ur-point.firebaseapp.com',
    storageBucket: 'ur-point.appspot.com',
    measurementId: 'G-ZK2DFHC3KZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgATJD0svzHCGf2-jVJuWjkfhP1Rfejtc',
    appId: '1:5042694816:android:7a24fd751d30db9187f7c5',
    messagingSenderId: '5042694816',
    projectId: 'ur-point',
    storageBucket: 'ur-point.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPNNj_Hl82DcAEMkjV4xU0oMZwo51mZLc',
    appId: '1:5042694816:ios:010aeca2d4264d7e87f7c5',
    messagingSenderId: '5042694816',
    projectId: 'ur-point',
    storageBucket: 'ur-point.appspot.com',
    iosClientId: '5042694816-hkgdbjv77iol0tll714s2p3b41pm21be.apps.googleusercontent.com',
    iosBundleId: 'com.urpoint.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPNNj_Hl82DcAEMkjV4xU0oMZwo51mZLc',
    appId: '1:5042694816:ios:2cdc1f5f3ddb399f87f7c5',
    messagingSenderId: '5042694816',
    projectId: 'ur-point',
    storageBucket: 'ur-point.appspot.com',
    iosClientId: '5042694816-uut37qodhgloji153g3laqcvki83dflu.apps.googleusercontent.com',
    iosBundleId: 'com.example.webView',
  );
}
